server:
  port: 8080

spring:
  application:
    name: Servico api com acesso ao banco de dados
  datasource:
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/servico_web_api
  #jpa:
    #generate-ddl: true
    #show-sql: true
